name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  realm: ^20.1.1
  flutter_riverpod: ^2.6.1
  uuid:  ^4.4.2  #for Unique id   
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
